version: '3.3'

services:
  express:
    container_name: node_express
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
    - 27017:27017